baseURL = 'https://curlbook.ca/'
languageCode = 'en-CA'
title = 'CurlBook'
theme = 'anubis'
publishDir = 'docs'

[params.author]
name = "Andrew Flemming"

[params]
description = "CurlBook is intuitive and insightful performance analysis software for curling teams"
dateFormat = "2006-01-02"
locale = "en-CA"
colorTheme = "auto"
colorThemeSwitcher = false

#[[menu.main]]
#identifier = "home"
#name = "Home"
#url = "/"
#weight = 1

#[[menu.main]]
#identifier = "how-to"
#name = "How To"
#url = "/posts/"
#weight = 2