baseURL = 'https://curlbook.ca/'
languageCode = 'en-CA'
title = 'CurlBook'
theme = 'anubis'
publishDir = 'docs'

[params.author]
name = "Andrew Flemming"

#[[menu.main]]
#identifier = "home"
#name = "Home"
#url = "/"
#weight = 1

#[[menu.main]]
#identifier = "how-to"
#name = "How To"
#url = "/posts/"
#weight = 2